# .github/workflows/build-and-push-docker.yml

name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Test Backend"]
    types:
      - completed

jobs:
  build-and-push-docker-image:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-22.04

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      # Login to DockerHub
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}

      # Build and push backend image
      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./simple-api
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/tp-git_backend:latest
          push: true

      # Build and push database image
      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: ./database
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/tp-git_database:latest
          push: true

      # Build and push httpd image
      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          context: ./http-server
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/tp-git_httpd:latest
          push: true

